name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv .venv
        uv sync

    - name: Debug environment
      run: |
        echo "Current directory: $(pwd)"
        echo "Python path: $(which python)"
        echo "Python version: $(python --version)"
        echo "Pytest version: $(.venv/bin/pytest --version)"
        echo "Listing test directory:"
        ls -la tests/
        ls -la tests/lib/

    - name: Test with pytest
      run: |
        .venv/bin/pytest tests/ -v --cov=src --cov-report=xml

    - name: Upload coverage to GitHub
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
